### PR TITLE
Utilize pytest-xdist and its --boxed option

### PR DESCRIPTION
**Pull request by lydia-duncan**
This allows tests to run in independent subprocesses, which prevents
materialization conflicts between tests as well as the issue I was seeing with
some of the numpy examples where the test following them segfaulted.

This should not hide materialization conflicts within a test, nor should it hide
segfaults within a test.  Both the errors mentioned above were in part a
result of pytest's run being a single process and thus maintaining all the
state present, even when different tests were executed.  We want pychapel
to maintain state within a single process, so that we don't have to
rematerialize a function if we desire to run it multiple times in a program.

Note that since the tests which experienced materialization conflicts obtained
their chapel functions through different files, this implies that we should
consider maintaining knowledge of the file from which the function has been
obtained, so that such materialization conflicts can be avoided.  I will create
a test to exercise this particular case and file a related issue.  Even though
pytest was the case which informed us of this particular issue, it is better to
silence the error from that forum (as the cause is less immediately clear) and
express it through a particular test.

### CODE REVIEW

**Comment by thomasvandoren** [comment]
:+1:

**Comment by thomasvandoren** [comment]
Looks good

**Comment by thomasvandoren** [comment]
Do you need to update pych --testing too? Or are you planning to get rid of that?

**Comment by lydia-duncan** [comment]
The tests it exercises don't require this at the moment (as all the function names they access are unique) and I haven't thought about the direction for pych --testing yet, so I think waiting seems reasonable.

**Comment by lydia-duncan** [comment]
Side tangent of note: pytest-xdist has the ability to run multiple tests at a time by specifying -n NUM, would we want to add that now?

**Comment by thomasvandoren** [comment]
Sure, does it have a way to set `-n` to the cpu count? Otherwise, you could use `nproc` or the python call we use in nightly et al.

**Comment by lydia-duncan** [comment]
That Travis failure did not make any sense whatsoever.  If it repeats itself, I will revert the parallel portion

**Comment by lydia-duncan** [comment]
Either the method of determining CPUs is inaccurate for Travis, or pytest-xdist -n runs roughshod over Travis.  In either case, push the part that seems to work.

**Pull request merged**
