### PR TITLE
Add copyright/license block to source files

### PR DESCRIPTION
**Pull request by awallace-cray**

### CODE REVIEW

**Comment by awallace-cray** [comment]
The idea was to add this to PR #90, for release to PyPi as pychapel 0.1.18. 
Or not - your call.

**Comment by lydia-duncan** [comment]
This seems fine to me.  Are you planning on adding a script that verifies all relevant source files have this copyright, like we have for the main repository?

**Comment by awallace-cray** [comment]
> adding a script that verifies all relevant source files have this copyright?
Filing that next to, 
change the nightly build/test job (or add a new one) to test installing with pip

**Comment by awallace-cray** [comment]
Rejected per BRob

**Pull request closed without merging**
